name: Run Tests

on:
  push: {}

jobs:
  test:
    name: CDK Tests
    runs-on: ubuntu-20.04
    container:
      image: "node:14"
    steps:
      - name: 💾 Checkout code
        uses: actions/checkout@v2
      - name: 🔧 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - name: 🏃🏻 Run NPM Tests
        run: |
          npm ci
          npm run test
